employees_index:
    path:     /
    defaults: { _controller: "KlapBundle:Employees:index" }
    methods:  GET

employees_show:
    path:     /{id}/show
    defaults: { _controller: "KlapBundle:Employees:show" }
    methods:  GET

employees_new:
    path:     /new
    defaults: { _controller: "KlapBundle:Employees:new" }
    methods:  [GET, POST]

employees_edit:
    path:     /{id}/edit
    defaults: { _controller: "KlapBundle:Employees:edit" }
    methods:  [GET, POST]

employees_delete:
    path:     /{id}/delete
    defaults: { _controller: "KlapBundle:Employees:delete" }
    methods:  DELETE
