category_video_index:
    path:     /
    defaults: { _controller: "KlapBundle:category_video:index" }
    methods:  GET

category_video_show:
    path:     /{id}/show
    defaults: { _controller: "KlapBundle:category_video:show" }
    methods:  GET

category_video_new:
    path:     /new
    defaults: { _controller: "KlapBundle:category_video:new" }
    methods:  [GET, POST]

category_video_edit:
    path:     /{id}/edit
    defaults: { _controller: "KlapBundle:category_video:edit" }
    methods:  [GET, POST]

category_video_delete:
    path:     /{id}/delete
    defaults: { _controller: "KlapBundle:category_video:delete" }
    methods:  DELETE
