formulaire_index:
    path:     /
    defaults: { _controller: "KlapBundle:Formulaire:index" }
    methods:  GET

formulaire_show:
    path:     /{id}/show
    defaults: { _controller: "KlapBundle:Formulaire:show" }
    methods:  GET

formulaire_new:
    path:     /new
    defaults: { _controller: "KlapBundle:Formulaire:new" }
    methods:  [GET, POST]

formulaire_edit:
    path:     /{id}/edit
    defaults: { _controller: "KlapBundle:Formulaire:edit" }
    methods:  [GET, POST]

formulaire_delete:
    path:     /{id}/delete
    defaults: { _controller: "KlapBundle:Formulaire:delete" }
    methods:  DELETE
