testimony_index:
    path:     /
    defaults: { _controller: "KlapBundle:Testimony:index" }
    methods:  GET

testimony_show:
    path:     /{id}/show
    defaults: { _controller: "KlapBundle:Testimony:show" }
    methods:  GET

testimony_new:
    path:     /new
    defaults: { _controller: "KlapBundle:Testimony:new" }
    methods:  [GET, POST]

testimony_edit:
    path:     /{id}/edit
    defaults: { _controller: "KlapBundle:Testimony:edit" }
    methods:  [GET, POST]

testimony_delete:
    path:     /{id}/delete
    defaults: { _controller: "KlapBundle:Testimony:delete" }
    methods:  DELETE
