<?php

namespace KlapBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryVideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryVideoRepository extends EntityRepository
{
    public function findElementById($id)
    {
        $req = $this->createQueryBuilder('cv')
            ->select()
            ->join('KlapBundle\Entity\IntegrationVideo', 'vc', 'WITH', 'cv.id = vc.video' )
            ->where('vc.video = ?1')
            ->setParameter(1, $id)
            ->getQuery();

        return $req->getResult();
    }
}
