<?php

namespace KlapBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * IntegrationVideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IntegrationVideoRepository extends EntityRepository
{
}
