<?php

namespace KlapBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * IntegrationVideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IntegrationVideoRepository extends EntityRepository
{
    public function findVideoByCategory($categoryId)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT v, c FROM KlapBundle:IntegrationVideo v
                 JOIN v.category_video c
                 WHERE v.id = :id'
            )->setParameter('id', $categoryId);
        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
