<?php

namespace KlapBundle\Repository;

/**
 * category_videoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class category_videoRepository extends \Doctrine\ORM\EntityRepository
{
}
