<?php

namespace KlapBundle\Repository;

/**
 * Integration_videoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Integration_videoRepository extends \Doctrine\ORM\EntityRepository
{
}
