# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    admin.formulaire:
        class: KlapBundle\Admin\FormulaireAdmin
        arguments: [~, KlapBundle\Entity\Formulaire, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Formulaire }

    admin.testimony:
        class: KlapBundle\Admin\TestimonyAdmin
        arguments: [~, KlapBundle\Entity\Testimony, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Testimony }

    admin.category_video:
        class: KlapBundle\Admin\category_videoAdmin
        arguments: [~, KlapBundle\Entity\category_video, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: category }

    admin.integration_video:
        class: KlapBundle\Admin\Integration_videoAdmin
        arguments: [~, KlapBundle\Entity\Integration_video, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Integration }